---

# cloudia-4man Basic Configuration
ansible_user: "your-superuser"

# Operating System Local Configuration
os_local:
  time_zone: "Europe/Zurich"
  keyboard:
    model: "pc105"
    layout: "ch"
    variant: ""
    options: ""
    backspace: "guess"
