---

# Configuration of K3s Cluster <k3s_cluster1>
k3s:
  # K3s release
  version: v1.32.3+k3s1
  # K3s server token
  token: "k3s_cluster1"
  api:
    loadbalancer: kube-vip # none | external | kube-vip (https://kube-vip.io/docs/usage/k3s/)
    endpoint: "192.168.1.10" # none: option doesn't affect anything
  # Networking:
  network:
    use: flannel
    flannel:
      # which interface should be used to talk with other cluster members
      iface: enp1s0 # -> flannel-iface
      # if dual-stack, than define IPv4 and IPv6 subnets separated by comma ',' (https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking)
      node-cidr-mask-size-ipv4:
      node-cidr-mask-size-ipv6:
      cluster-cidr: 10.42.0.0/16,2001:cafe:42::/56
      service-cidr: 10.43.0.0/16,2001:cafe:43::/112
  storage:
    use:
      - local
      - longhorn
    local:
      # Local Path Provisionier: https://github.com/rancher/local-path-provisioner/blob/master/README.md#usage
      data-path: /opt/local-path-provisioner
    longhorn:
      # Longhorn Storage: https://longhorn.io/docs/1.8.1/references/settings/#default-data-path
      data-path: /var/lib/longhorn
  ingress:
    # An ingress controller routes traffic based on requested URI to the right pod/container.
    # K3s default: traefik
    # Recommandation: use NGINX as ingress and reverse-proxy with OWASP
    # Read more:
    # - https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/)
    # - https://blog.opensight.ch/zerotrust-kubernetes-nginx-ingress-hardening-mit-mod_security-waf-und-owasp-crs/
    use: nginx # nginx | traefik
  loadbalancer:
    # A load balancer expose services, which could be routed and handled by ingress controller, to the external world.
    # K3s default: servicelb
    # Recommandation: use Kube-VIP as (real) load balancer for services AND control plane
    # Read more:
    # - https://kube-vip.io/
    # - https://github.com/k3s-io/k3s/discussions/9255
    use: kube-vip # kube-vip | metallb | servicelb
    kube-vip:
      
    # metallb:
    #  vip: 192.168.123.130-192.168.123.139
      
