---
# Configuration of all admin_nodes
# - none: no installation needed; v0.4.27: version to be installed (please use official release tags) 
admin_tools:
  - name: "kubectl"
    version: "v1.35.0"
  - name: "etcdctl"
    version: "v3.6.10"
  - name: "mqttx"
    version: "v1.13.0"
  - name: "k9s"
    version: "v0.51.0"
  #- name: "trufflehog"
  #  version: "none"
  #- name: "k8sgpt"
  #  version: 'none'
  #- name: "ansible
  #  version: 'none'
