---

# Template for Raspberry Pi 4 devices
# - add each device - that is a Raspberry Pi 4 device - to the predefined group <raspberrypi_4_devices>
raspberrypi_4_devices:
  hosts:
    <server>[1:3]:

# Template for a K3s cluster environment
# - for each k3s cluster create a group named by cluster-name, and add related servers as children of this group
k3s_cluster1:
  hosts:
    <server1>:
    <server2>:
    <server3>:
    <server4>:
    <server5>:
    <server6>:

# Template for Zigbee2MQTT proxies
# - add each server - that has a ZigBee Z-stack USB stick attached - to the predefined group <zigbee2mqtt_proxies>
zigbee2mqtt_proxies:
  hosts:
    <server1>:
