---

# Template for plain servers
# - add each server, which needs to be handled like a plain server (only OS level will be managed) to the predefined group <plain_servers>
plain_servers:
  hosts:
    <server>[1:3]:

# Template for a K3s cluster environment
# - for each k3s cluster create a group named by cluster-name, and add related servers as children of their corresponding role
k3s_cluster1:
  children:
    k3s_servers:
      hosts:
        <server1>:
        <server2>:
        <server3>:
    k3s_agents:
      hosts:
        <server4>:
        <server5>:
        <server6>:

# Template for Zigbee2MQTT proxies
# - add each server - that has a ZigBee Z-stack USB stick attached - to the predefined group <zigbee2mqtt_proxies>
zigbee2mqtt_proxies:
  hosts:
    <server1>:
