---
# Role: os_basic
# supported operating systems:
# - Ubuntu

- name: 'Change time zone'
  timezone:
    name: "{{time_zone}}"

- name: 'Change keyboard layout'
  become: yes
  template:
    src: ../template/keyboard.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: 'Template out Netplan YAML to configure networking'
  template:
    src: ../templates/netplan.99_config.yaml.j2
    dest: /etc/netplan/99_config.yaml
  when: ansible_os_family == 'Ubuntu'

- name: 'Applying Netplan Configuration'
  command: netplan apply
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Ubuntu'

- name: 'Upgrade the OS (apt-get dist-upgrade)'
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Ubuntu'
 
- name: 'Update all packages to latest versions'
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Ubuntu'
  become: yes
