---
# Role: os_basic
# supported operating systems:
# - Ubuntu

- name: 'Change time zone'
  community.general.timezone:
    name: "{{time_zone}}"

- name: 'Change keyboard layout'
  become: yes
  ansible.builtin.template:
    src: ../template/keyboard.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: 'os_basic tasks for OS Ubuntu'
  import_tasks: os_basic_ubuntu.yml
  when: ansible_facts['os_family']|lower == 'ubuntu'

# - name: 'os_basic tasks for OS RedHat'
#  import_tasks: os_basic_redhat.yml
#  when: ansible_facts['os_family']|lower == 'redhat'

