---
# Role: os_basic
# supported operating systems:
# - Ubuntu

- name: 'Change time zone'
  community.general.timezone:
    name: "{{ os_basic.time_zone }}"
- name: 'Restart time-dependent services'
  ansible.builtin.service:
    name: cron
    state: restarted

- name: 'Change keyboard layout'
  become: yes
  ansible.builtin.template:
    src: os-basic-keyboard.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'

# change sudoers
# sudo: ALL=(ALL) NOPASSWD:ALL

# add public key to authorized keys:
# ssh_authorized_keys:
# - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsUa+TiDLpHAEq8XWyUSeAku7A5WRhl1AT2wK3ltb12+exqsnvp2NKNmcD3Ind0t4/SHqAIp8ihHAF+oYyv3eFvpCIAL0TrXl/UhgEDcu3/MyLQYYwKeKQ/SjxezLraTBYzHLYne3zBBsX7FqyU1v4TU9OmH8RAS0jYYEM8GeCR4RztFnf9+wgIJjMW0jbBTw42AutKWjcYDOnTxqei2gEEQvnYn36CoawX1tZ/4J8AMvypcZOiJXuw3r8MU1a6o8WLFO9o3pt/pNSBQs9lTFaNFEgeRSOxqpBSikQSfleQ35y/Q3nWk8oZIavptf4vm+XCbswlKAsB/RDGbIq4l57bXwEHg8Y4rx72NO38WruDnkEsZc0CchtTHFiCpcSDd4iKIZFyu9o5zXTkkLwUHIoq64BLhf0X3fdrdLaX9QwqyqB1EMFiWqsAz3TSF0L516zpMWhsbhyXn2JhBl2HseFPI5+yAUOrQnlxCdJvMaH2hWKJeZB8B226TbqbQ+5PGc= oso@snarloso

- name: 'os_basic tasks for OS family Debian (Debian/Ubuntu)'
  import_tasks: os_basic_family_debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

# - name: 'os_basic tasks for OS RedHat'
#  import_tasks: os_basic_redhat.yaml
#  when: ansible_facts['os_family']|lower == 'redhat'

