---

- name: 'Template out Netplan YAML to configure networking'
  ansible.builtin.template:
    src: ../templates/netplan.99_config.yaml.j2
    dest: /etc/netplan/99_config.yaml
  become: yes

- name: 'Applying Netplan Configuration'
  ansible.builtin.command: netplan apply
  become: yes
  become_method: sudo

# SYSTEM AND PACKAGE UPDATES
# "sudo apt-get update -y",
# "sudo apt-get upgrade -y",
# "sudo apt-get dist-upgrade -y",
# "sudo apt --fix-broken install -y",
- name: 'Upgrade the OS (apt-get dist-upgrade)'
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: 'Install basic packages'
  ansible.builtin.apt:
    update_cache: yes
    autoremove: yes
    state: present
    pkg:
      - vim

- name: 'Update all packages to latest versions'
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes
