---

- task: 'Preparing Terraform project for Raspberry Pi 4 device (locally)'
  local_action:
    module: ansible.builtin.template:
    src: ../template/main.tf.j2
    dest: {{ inventory_dir }}/{{ inventory_host }}/main.tf
    
- task: 'Provisioning Raspberry Pi 4 device'
  community.general.terraform:
    project_path: {{ inventory_dir }}/{{ inventory_host }}/main.tf
 
