---
# k3s_components:flannel:tasks
# based on: 
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/manifests"
    state: directory
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Check, if interface exists for flannel
  command: "ip link show {{ k3s.networking.flannel.iface }}"
  register: _cmd_ip_link_show_flannel_iface
  ignore_errors: true
  changed_when: false

### Prepare configuration to use flannel for network
# CONDITION: Environment defines the usage of flannel for network
- name: Prepare configuration to use flannel for network
  when: _cmd_ip_link_show_flannel_iface.rc == 0 and k3s.networking.use == 'flannel'
  block:
    - name: Generate nic parameters for flannel
      ansible.builtin.set_fact:
        _k3s_network_flannel_ipaddress: "169.254.{{ {{ os_network.ip4.address }}.split('.')[2] | default('1') }}.{{ {{ os_network.ip4.address }}.split('.')[3] | default('1') }}"
        _k3s_network_flannel_ipprefix: "{{ os_network.ip4.cidr | default('24') }}"
      # when: ansible_host is defined and ansible_interfaces is defined
    - name: Create netplan configuration for flannel
      become: true
      template:
        src: "flannel-netplan.yaml.j2"
        dest: "/etc/netplan/50-k3s-network-flannel.yaml"
    - name: Apply netplan configuration for flannel
      become: true
      command: netplan apply
    - name: Add K3s config file for flannel
      become: true
      template:
        src: "flannel-{{ ansible_parent_role_names[0] }}-config.yaml.j2"
        dest: "/etc/rancher/k3s/config.yaml.d/50-k3s-network-flannel.yaml"
      
