---
# k3s_components:flannel:tasks
# based on: 
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: "0755"

- name: Check, if interface exists for flannel
  command: "ip link show {{ k3s.network.flannel.iface }}"
  register: _cmd_ip_link_show_flannel_iface
  ignore_errors: true
  changed_when: false

### Prepare configuration to use flannel for network
# CONDITION: Environment defines the usage of flannel for network
- name: Prepare configuration to use flannel for network
  when: not ansible_check_mode and _cmd_ip_link_show_flannel_iface.rc == 0 and k3s.network.use == "flannel"
  block:
    - name: Generate nic parameters for flannel
      ansible.builtin.set_fact:
        _fact_nic_primary: "{{ ansible_interfaces | select(ansible_interfaces | map(attribute='ipv4') | map('contains', ansible_host)) | first | default(omit) }}"
        _fact_nic_primary_ipaddress: "{{ ansible_{{ _fact_nic_primary }}.ipv4.address | default({}) }}"
        _fact_nic_flannel_ipaddress: "169.254.{{ _fact_nic_primary_ipaddress.split('.')[2] | default('1') }}.{{ _fact_nic_primary_ipaddress.split('.')[3] | default('1') }}"
        _fact_nic_flannel_ipprefix: "{{ ansible_{{ _fact_nic_primary }}.ipv4.prefix | default('24') }}"
      # when: ansible_host is defined and ansible_interfaces is defined
    - name: Create netplan configuration for flannel
      become: true
      template:
        src: flannel-netplan.yaml.j2
        dest: /etc/netplan/50-k3s-network-flannel.yaml
    - name: Apply netplan configuration for flannel
      become: true
      command: netplan apply
    - name: K3s configuration
      
