---
# k3s_components:kube-vip:tasks
# based on: https://kube-vip.io/docs/usage/k3s/
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: '0755'

- name: Download kube-vip RBAC manifest
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    timeout: 120
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
    owner: root
    group: root
    mode: "0755
