---
# k3s_components:kube-vip:tasks
# based on: https://kube-vip.io/docs/usage/k3s/
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/manifests"
    state: directory
    mode: "0755"

### Prepare configuration to use kube-vip for control-plane
# CONDITION: Environment defines the usage of kube-vip for control-plane
- name: Prepare configuration to use kube-vip for control-plane
  when: k3s.api.loadbalancer == 'kube-vip'
  block:
    - name: Download kube-vip RBAC manifest
      ansible.builtin.get_url:
        url: "https://kube-vip.io/manifests/rbac.yaml"
        timeout: 120
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-api-rbac.yaml"
        mode: "0644"
      when: not ansible_check_mode
    - name: Create kube-vip DeamonSet manifest
      ansible.builtin.template:
        src: "kube-vip-api-deamonset.yaml.j2"
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-api-deamonset.yaml"
        mode: "0644"

### Prepare configuration to use kube-vip for service load balancing
# CONDITION: Environment defines the usage of kube-vip for service load balancing
- name: Prepare configuration to use kube-vip for service load balancing
  when: k3s.loadbalancer.addon == 'kube-vip'
  block:
    - name: Download kube-vip Cloud Controller manifest
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml"
        timeout: 120
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-slb-cloud-controller.yaml"
      when: not ansible_check_mode
    - name: Create kube-vip ConfigMap manifest
      ansible.builtin.template:
        src: "kube-vip-slb-configmap.yaml.j2"
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-slb-configmap.yaml"
        mode: "0644"
    - name: Prevent default configuration of K3s load balancer servicelb
      ansible.builtin.file:
        path: "/var/lib/rancher/k3s/server/manifests/servicelb.yaml.skip"
        state: touch
