


  - name: Prepare data folders for local-storage provisioner
    ansible.builtin.file:
      path: "{{ k3s.storage.local-provisioner.path }}"
      state: directory
      mode: "0755"
  - name: Prepare data folders for local-storage provisioner
     ansible.builtin.file:
       src: "{{ k3s.storage.local-provisioner.path }}"
       dest: "/k3s-data/local-storage-provisioner"
       state: link
