---
# k3s_components:longhorn:tasks
# based on: 
# https://longhorn.io/docs/1.9.0/advanced-resources/os-distro-specific/csi-on-k3s/
# - install open-iscsi
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/manifests"
    state: directory
    mode: "0755"

### Prepare configuration to use longhorn for storage
# CONDITION: Environment defines the usage of longhorn for storage
- name: Prepare configuration to use longhorn for storage
  when: "'longhorn' in (k3s.storage.provisioners | default([]))"
  block:
    - name: Prepare data folders for longhorn
      ansible.builtin.file:
        path: "{{ k3s.storage.longhorn.data_path }}"
        state: directory
        mode: "0755"
    - name: Prepare data folders for longhorn
      ansible.builtin.file:
        src: "{{ k3s.storage.longhorn.data_path }}"
        dest: "/k3s-data/longhorn"
        state: link
      when: not ansible_check_mode
    - name: Install pre-requisites for Longhorn on all K3s nodes based on Debian OS family (Ubuntu/Debian)
      when: ansible_os_family|lower == 'debian'
      ansible.builtin.apt:
        name:
          - open-iscsi
          - nfs-common
        state: present
        update_cache: yes
    - name: Install pre-requisites for Longhorn on all K3s nodes based on Red Hat OS family (RHEL/CentOS)
      when: ansible_os_family|lower == 'redhat'
      ansible.builtin.yum:
        name:
          - iscsi-initiator-utils
          - nfs-utils
        state: present
        update_cache: yes
