---
## Before upgrading:
# Check 1: Ensure that all V2 Data Engine volumes are detached and the replicas are stopped. The V2 Data Engine currently does not support live upgrades.
# Check 2: Avoid upgrading when volumes are in the “Faulted” status. If all the replicas are deemed unusable, they may be deleted and data may be permanently lost (if no usable backups exist).
# Check 3: Avoid upgrading if a failed BackingImage exists. For more information, see Backing Image.
# Backup: It is recommended to create a Longhorn system backup before performing the upgrade. This ensures that all critical resources, such as volumes and backing images, are backed up and can be restored in case any issues arise.
#====
# - name: "deploy prerequisites"
#  kubernetes.core.k8s:
#    state: present
    # src: 'rauthy-prerequisites.yaml'
    # definition: |-
    # template: 'rauthy-prerequisites.yaml.j2'
    # - path: 'file1.j2'
    # - path: 'file2.j2'
- name: 'deploy app Longhorn'
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/longhorn/longhorn/{{ k3s.storage.longhorn.version }}/deploy/longhorn.yaml"
- name: 'deploy configuration for Longhorn'
  kubernetes.core.k8s:
    state: present
    template: 'longhorn.yaml.j2'
- name: 'configure ingress for Longhorn Dashboard'
  kubernetes.core.k8s:
    state: present
    template: 'longhorn-ingress-{{ k3s.ingress.controller }}.yaml.j2'
