---
- name: Deploy K3s components
  # become_user: root -> run as root (default)
  # ignore_errors: true
  block:
    - name: Deploy K3s network flannel
      when: k3s.networking.addon == 'flannel'
      ansible.builtin.include_tasks: flannel_k3s-level.yaml
    - name: Deploy K3s storage local-path-provisioner
      when: "'local' in (k3s.storage.provisioners | default([]))"
      ansible.builtin.include_tasks: local-path-provisioner_k3s-level.yaml
    - name: Deploy K3s storage longhorn
      when: "'longhorn' in (k3s.storage.provisioners | default([]))"
      ansible.builtin.include_tasks: longhorn_k3s-level.yaml
    - name: Deploy K3s ingress controller nginx
      when: k3s.ingress.controller == 'nginx'
      ansible.builtin.include_tasks: nginx_k3s-level.yaml
    - name: Deploy K3s ingress controller traefik
      when: k3s.ingress.controller == 'traefik'
      ansible.builtin.include_tasks: traefik_k3s-level.yaml
    - name: Deploy K3s loadbalancer kube-vip
      when: k3s.api.loadbalancer == 'kube-vip' or k3s.loadbalancer.addon == 'kube-vip'
      ansible.builtin.include_tasks: kube-vip_k3s-level.yaml
