---
# k3s_components:nginx:tasks
# based on: 
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: "0755"

### Prepare configuration to use nginx for ingress
# CONDITION: Environment defines the usage of nginx for ingress
- name: Prepare configuration to use nginx for ingress
  when: not ansible_check_mode and (k3s.ingress.use == "nginx")
  block:
    - name: Download nginx ingress manifest
      ansible.builtin.get_url:
        url: 
        timeout: 120
        dest: 
      become: yes
    - name: Create kube-vip ConfigMap manifest
      ansible.builtin.template:
        src: ../templates/kube-vip-configmap.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-configmap.yaml
      become: yes
    - name: Prevent configuration of K3s ingress traefik
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
        state: touch
      become: yes
