---
# k3s_components:nginx:tasks
# based on: https://kube-vip.io/docs/usage/k3s/
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: "0755"

### Prepare configuration to use nginx for ingress controller
# CONDITION: Environment defines the usage of nginx for ingress controller
- name: Prepare configuration to use nginx for ingress controller
  when: not ansible_check_mode and k3s.ingress.controller == "nginx"
  become: yes
  block:
    #- name: Download kube-vip Cloud Controller manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
        timeout: 120
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml
    #- name: Create kube-vip ConfigMap manifest
      ansible.builtin.template:
        src: ../templates/kube-vip-configmap.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-configmap.yaml
    - name: Prevent default configuration of K3s ingress controller traefik
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
        state: touch
