---
# k3s_components:nginx:tasks
# based on: 
#
- name: If K3s manifest folder does not exist, create K3s manifest folder
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/manifests"
    state: directory
    owner: root
    group: root
    mode: "0644"
  become: yes

### Prepare configuration to use nginx for ingress controller
# CONDITION: Environment defines the usage of nginx for ingress controller
- name: Prepare configuration to use nginx for ingress controller
  when: k3s.ingress.controller == 'nginx'
  become: yes
  block:
    - name: Prevent default configuration of K3s ingress controller traefik
      ansible.builtin.file:
        path: "/var/lib/rancher/k3s/server/manifests/traefik.yaml.skip"
        state: touch
