---
# Role: device_rpi4
# Raspberry Pi 4 device-specific configuration

- name: 'Adjust GPU Memory'
    lineinfile:
      path: /boot/config.txt
      line: 'gpu_mem=16'
      state: present
    tags: [ device_rpi4_gpu ]

- name: 'Disable audio'
    lineinfile:
      path: /boot/config.txt
      line: 'dtparam=audio=off'
      state: present
    tags: [ device_rpi4_audio ]
 
 # if USB disk is present
    - file: { path: /mnt/nvme1, state: directory }
      tags: [ device_rpi4_nvme1 ]
      
    - name: '/etc/fstab'
      lineinfile:
        path: /etc/fstab
        line: 'UUID=240A-1CED  /ext-disk  vfat   auto,nofail,noatime,rw,exec,uid=plex,gid=plex,nouser,async  0 0'
        regexp: ^.*\/ext-disk
      register: fstab
      tags: [ device_rpi4_nvme1 ]
