---
# Configuration of K3s Cluster <k3s_cluster1>
k3s:
  # K3s release
  version: "v1.32.3+k3s1"
  # K3s server token
  token: "k3s_cluster.token"
  api:
    loadbalancer: "kube-vip" # none | external | kube-vip (if kube-vip, please define parameters under section "loadbalancer")
    endpoint: "api.k3s_cluster.fqdn" # if loadbalancer = "none", than first server in environment will be used.
    vip: "192.168.1.10"
    # port: "6443" # if changed, please be aware about possible incompatiblities by other K8s components/operators and so on.
  # Networking:
  networking:
    # if dual-stack, than define IPv4 and IPv6 subnets separated by comma ',' (https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking)
    # cluster_cidr: 10.42.0.0/16,2001:cafe:42::/56
    # service_cidr: 10.43.0.0/16,2001:cafe:43::/112
    # node_cidr_mask_size_ipv4:
    # node_cidr_mask_size_ipv6:
    addon: "flannel" # none
    flannel:
      # flannel-iface: which interface should be used to talk with other cluster members
      iface: "enp1s0"
  storage:
    # disk: 
    data_size: 256g
    provisioners:
      - local
      - longhorn
    local:
      # Local Path Provisionier: https://github.com/rancher/local-path-provisioner/blob/master/README.md#usage
      data_path: /opt/local-path-provisioner
    longhorn:
      # Longhorn Storage: https://longhorn.io/docs/1.8.1/references/settings/#default-data-path
      version: "v1.10.2"
      data_path: /var/lib/longhorn
      dashboard:
        fqdn: "longhorn.k3s_cluster.fqdn"
  ingress:
    # An ingress controller routes traffic based on requested URI to the right pod/container.
    # K3s default: traefik
    # Recommendation: use traefik and nginx-waf as sidecar (bc nginx-ingress-controller isn't supported anymore since March 2026)
    # Read more:
    # - https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/)
    # - https://blog.opensight.ch/zerotrust-kubernetes-nginx-ingress-hardening-mit-mod_security-waf-und-owasp-crs/
    controller: "nginx" # nginx | traefik
    nginx:
      # version: "v0.0.0"
    traefik:
      # version: "v0.0.0"
      dashboard:
        fqdn: "traefik.k3s_cluster.fqdn"
        ipallowlist:
          - "192.168.123.0/25"
          - "2a02:169:67f5:1af::/64"
  loadbalancer:
    # A load balancer expose services, which could be routed and handled by ingress controller, to the external world.
    # K3s default: servicelb
    # Recommandation: use Kube-VIP as (real) load balancer for services AND control plane (if configured under section "api")
    # Read more:
    # - https://kube-vip.io/
    # - https://github.com/k3s-io/k3s/discussions/9255
    addon: "kube-vip" # kube-vip | metallb | servicelb
    kube_vip:
      # https://kube-vip.io/docs/usage/k3s/ / https://kube-vip.io/docs/installation/daemonset/)
      lb_version: v0.4.0
      lb_range: "192.168.123.130-192.168.123.139"
      api_version: v0.9.1
      api_iface: "enp0s0"
    # metallb:
    #  lb_range: "192.168.123.130-192.168.123.139"

k8s_apps:
  - name: "kubernetes-reflector"
    version: "none" # v10.0.3
  - name: "cert-manager"
    version: "none" # v1.19.2
    acme:
      email: "hostmaster@fqdn"
  - name: "home-assistant"
    version: "none" # 2026.1.0
    namespace: "home-assistant"
    mode: "prod" # test
    config:
      fqdn: "home-assistant.fqdn"
      country: "CH"
      language: "de"
      currency: "CHF"
      time_zone: "Europe/Zurich"
    storage:
      class_name: "longhorn"
      size: "16Gi"
  - name: "mosquitto"
    version: "none" # 2.1.2
    namespace: "mosquitto"
    mode: "prod" # test
    mqtt:
      fqdn: "mosquitto.fqdn"
  - name: "zigbee2mqtt"
    version: "none" # 2.8.0
    namespace: "zigbee2mqtt"
    mode: "prod" # test
    frontend:
      fqdn: "zigbee2mqtt.fqdn"
    zigbee:
      channel: "11"
      pan_id: "0x1a62"
      ext_pan_id: "[0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]"
    mqtt:
      server_url: "mqtt://mosquitto-service.mosquitto.svc:1883" # mqtts://mosquitto-public.fqdn:8883
    storage:
      class_name: "longhorn"
      size: "1Gi"
    serial:
      port: "/dev/serial/by-id/<SERIAL_ID>" # /dev/ttyUSB0
      adapter: "zstack" # see https://www.zigbee2mqtt.io/guide/adapters/
  - name: "gatus"
    version: "none" # 
    namespace: "gatus"
    mode: "prod" # test
    frontend:
      fqdn: "gatus.fqdn"
    endpoints:
    - name: "example"
      url: "https://example.org"
      interval: "60s"
      conditions:
        - "[STATUS] == 200"
        - "[BODY] == pat(*<h1>Example Domain</h1>*)"
  #- name: name - required
  #  version: version - required
  #  namespace: namespace
  #  mode: "prod" # test
  #  params:
  #    x: y
  #  param: value
