---
# Configuration of K3s Cluster <k3s-cluster1>
k3s:
  # K3s release
  version: "v1.35.4+k3s1"
  # K3s server token
  token: "k3s_cluster.token"
  api:
    loadbalancer: "kube-vip" # none | external | kube-vip (if kube-vip, please define parameters under section "loadbalancer")
    endpoint: "api.k3s_cluster.fqdn" # if loadbalancer = "none", than first server in environment will be used.
    vip: "192.168.1.10"
    # port: "6443" # if changed, please be aware about possible incompatiblities by other K8s components/operators and so on.
  # Networking:
  networking:
    # if dual-stack, than define IPv4 and IPv6 subnets separated by comma ',' (https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking)
    # cluster_cidr: 10.42.0.0/16,2001:cafe:42::/56
    # service_cidr: 10.43.0.0/16,2001:cafe:43::/112
    # node_cidr_mask_size_ipv4:
    # node_cidr_mask_size_ipv6:
    addon: "flannel" # none
    flannel:
      # flannel-iface: which interface should be used to talk with other cluster members
      iface: "enp1s0"
  storage:
    # disk: 
    data_size: 256g
    provisioners:
      - local
      - longhorn
    local:
      # Local Path Provisionier: https://github.com/rancher/local-path-provisioner/blob/master/README.md#usage
      data_path: /opt/local-path-provisioner
    longhorn:
      # Longhorn Storage: https://longhorn.io/docs/1.8.1/references/settings/#default-data-path
      version: "v1.11.2"
      data_path: /var/lib/longhorn
      dashboard:
        fqdn: "longhorn.k3s_cluster.fqdn"
      backup_target:
        type: "cifs" # cifs|nfs|aws-s3|gcp-storage|azure-blog|
        fqdn_path: "backup-target.fqdn/backupstore"
  ingress:
    # An ingress controller routes traffic based on requested URI to the right pod/container.
    # K3s default: traefik
    # Recommendation: use traefik and nginx-waf as sidecar (bc nginx-ingress-controller isn't supported anymore since March 2026)
    # Read more:
    # - https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/)
    # - https://blog.opensight.ch/zerotrust-kubernetes-nginx-ingress-hardening-mit-mod_security-waf-und-owasp-crs/
    controller: "nginx" # nginx | traefik
    nginx:
      # version: "v0.0.0"
    traefik:
      # version: "v0.0.0"
      dashboard:
        fqdn: "traefik.k3s_cluster.fqdn"
        ipallowlist:
          - "192.0.2.0/24"
          - "2001:0db8::/64"
  loadbalancer:
# A load balancer expose services, which could be routed and handled by ingress controller, to the external world.
    # K3s default: servicelb
    # Recommandation: use Kube-VIP as (real) load balancer for services AND control plane (if configured under section "api")
    # Read more:
    # - https://kube-vip.io/
    # - https://github.com/k3s-io/k3s/discussions/9255
    addon: "kube-vip" # kube-vip | metallb | servicelb
    kube_vip:
      # https://kube-vip.io/docs/usage/k3s/ / https://kube-vip.io/docs/installation/daemonset/)
      # lb_version: Check latest kube-vip Cloud Controller version https://github.com/kube-vip/kube-vip-cloud-provider
      lb_version: "v0.0.12"
      lb_range: "192.0.2.224-192.0.2.254"
      api_iface: "enp1s0"
      # api_version: Check latest kube-vip release on https://github.com/kube-vip/kube-vip
      api_version: "v1.1.2"
    # metallb:
    #  lb_range: "192.0.2.224-192.0.2.254"
