---
###
# WARNING: This is not for production usage!
###
# In a productive inventory, encrypt this file secrets.yaml by ansible-vault first.
# Afterwards, change all secrets with your own values.
#
# Eg.
# > ansible-vault encrypt secrets.yaml
# > ansible-vault edit secrets.yaml
vault_k3s:
  storage:
    longhorn:
      ui_username: "longhorn"
      ui_password: "longhorn"
