---
###
# WARNING: This is not for production usage!
###
# In a productive inventory, encrypt this file secrets.yaml by ansible-vault first.
# Afterwards, change all secrets with your own values.
#
# Eg.
# > ansible-vault encrypt secrets.yaml
# > ansible-vault edit secrets.yaml
vault_k3s:
  storage:
    longhorn:
      dashboard:
        username: "longhorn"
        password: "longhorn"

vault_k8s_apps:
  zigbee2mqtt:
    network_key: "[1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]"
    mqtt_user: "username"
    mqtt_password: "password"
