- name: 'Helper: K8s Ingress Detector'
  run_once: true
  when: k8s.ingress is not defined or k8s.ingress.class is not defined
  block:
    - name: "Get all ingress classes"
      kubernetes.core.k8s_info:
        kind: IngressClass
      register: _k8s_ingress_classes

    - name: "Select default ingress class (fallback: first one)"
      set_fact:
        k8s: >-
          {{
            k8s | default({}) | combine( { ingress { class: (
              _k8s_ingress_classes.resources
              | selectattr('metadata.annotations.ingressclass.kubernetes.io/is-default-class', 'defined')
              | map(attribute='metadata.name') | list
              + _k8s_ingress_classes.resources | map(attribute='metadata.name') | list
            ) | first | default('none')
          }}
        cacheable: true

    - name: "Warn user, if no ingress has been detected"
      when: k8s.ingress.class == 'none'
      debug:
        msg: "WARNING: No K8s ingress controller detected! Applications requiring one will fail."
