---
# More information about dictionary variables (https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#dictionary-variables)

# Template for server1
ip4:
  address: '192.168.0.24'
  cidr: '/24'
  gateway: '192.168.0.1'
  dns_server: '192.168.0.1'
ip6:
  address: '2001:DB8::24'
  cidr: '/64'
  gateway: '2001:DB8::1'
  dns_server: '2001:DB8::1'
dns_domain: 'example.org'
