---
# More information about dictionary variables (https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#dictionary-variables)

# Operating System Network configuration for server1
os_network:
  iface: enp1s0
  ip4:
    address: '192.168.0.24'
    cidr: '24'
    gateway: '192.168.0.1'
  ip6:
    address: '2001:DB8::24'
    cidr: '64'
    gateway: '2001:DB8::1'
  dns:
    domains:
      - 'example.org'
    servers:
      - '2001:DB8::1'
      - '192.168.0.1'
