---
    - name: "mqttx: prepare environment"
      ansible.builtin.file:
        path: "/tmp/mqttx"
        state: directory
    - name: "mqttx: downloading binaries"
      ansible.builtin.get_url:
        url: "https://www.emqx.com/en/downloads/MQTTX/{{ _admin_tool.version }}/mqttx-cli-linux-x64"
        dest: "/tmp/mqttx"
    - name: "mqttx: installing binaries"
      ansible.builtin.command:
        cmd: "install ./mqttx-cli-linux-x64 /usr/local/bin/mqttx"
      args:
        chdir: "/tmp/mqttx"
