---
- name: "tool k9s"
  when: _admin_tool.version != 'none'
  block:
    - name: "k9s: prepare environment"
      ansible.builtin.file:
        path: "/tmp/k9s"
        state: directory
    - name: "k9s: downloading binaries"
      ansible.builtin.get_url:
        url: "https://github.com/derailed/k9s/releases/download/{{ _admin_tool.version }}/k9s_Linux_arm64.tar.gz"
        dest: "/tmp/k9s_Linux_arm64.tar.gz"
    - name: "k9s: extracting binaries (tar -xzf k9s.tar)"
      ansible.builtin.unarchive:
        src: "/tmp/k9s_Linux_arm64.tar.gz"
        dest: "/tmp/k9s"
        remote_src: yes
    - name: "kubectl: installing binaries"
      ansible.builtin.command:
        cmd: "install -o root -g root -m 0755 k9s /usr/local/bin/k9s"
      args:
        chdir: "/tmp/k9s"
      become: true
