---
- name: "prepare environment"
  ansible.builtin.file:
    path: "/tmp/kubectl"
    state: directory
- name: "downloading binaries"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ admin_tools.kubectl.version }}/bin/linux/amd64/kubectl"
    dest: "/tmp/kubectl/"
- name: "installing binaries"
  ansible.builtin.command:
    cmd: "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
  args:
    chdir: "/tmp/kubectl"
  become: true
- name: "configuring kubectl - autocomplete"
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    regexp: '\.\s+<\(kubectl completion bash\)'
    line: ". <(kubectl completion bash)  # Added by k3s-ansible"
- name: "configuring kubectl - get kubeconfig"
  block:
    - name: "Test"
      ansible.builtin.file:
        path: "~/test-{{ groups['k3s_servers'][0] }}"
        state: touch
      delegate_to: "{{ groups['k3s_servers'][0] }}"

 - name: Inform user about KUBECONFIG environment variable
   ansible.builtin.debug:
     msg: |
       K3s Cluster and Kubeconfig has been set up.\n
       -------------------------------------------\n
        Please install kubectl for managing your K3s cluster:\n
         1. curl -LO 'https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl'\n
         2. install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl\n
          Please check the installation with following commands:\n
          - kubectl get nodes -l 'node-role.kubernetes.io/control-plane=true' -o=jsonpath='{.items[*].metadata.name}'\n
          Remember: Helm Controller is automatically installed.\n
