---
# Role: admin_node
# supported operating systems:
# - Ubuntu
- name: "Assert that the general default parameters for the role have been defined."
  ansible.builtin.assert:
    that:
      - admin_tools is not falsy
    fail_msg: "role admin_node: parameter admin_tools is not defined!"

- name: "Iterate through admin tools"
  include_tasks: 
    file: "admin_tools_{{ item.name }}.yaml"
  loop: "{{ admin_tools }}"
  loop_control:
    loop_var: item
    label: "{{ item.name }} ({{ item.version }})"
  vars:
    _admin_tool: "{{ item }}"


# change sudoers
# sudo: ALL=(ALL) NOPASSWD:ALL
