---
# Role: admin_node
# supported operating systems:
# - Ubuntu

# change sudoers
# sudo: ALL=(ALL) NOPASSWD:ALL

- name: "tool kubectl"
  when: admin_tools.kubectl.version != 'none'
  import_tasks: admin_node_tools_kubectl.yaml

- name: "tool k8sgpt"
  when: admin_tools.k8sgpt.version != 'none'
  block:
    - name: "downloading binaries"
      ansible.builtin.get_url:
        url: "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ admin_tools.k8sgpt.version }}/k8sgpt_Linux_x86_64.tar.gz"
        dest: "/tmp/k8sgpt_Linux_x86_64.tar.gz"
    - name: "extracting binaries (tar -xzf k8sgpt_Linux_x86_64.tar.gz)"
      ansible.builtin.unarchive:
        src: "/tmp/k8sgpt_Linux_x86_64.tar.gz"
        dest: "/tmp/k8sgpt"
        remote_src: yes
    - name: "installing binaries"
      ansible.builtin.copy:
        src: "/tmp/k8sgpt/k8sgpt"
        dest: "/usr/local/bin/k8sgpt"
      become: true
  # Original Source: https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.27/k8sgpt_Linux_x86_64.tar.gz


- name: 'admin_node tasks for Debian OS family (Debian/Ubuntu)'
  import_tasks: admin_node_family_debian.yaml
  when: ansible_os_family|lower == 'debian'

# - name: 'os_basic tasks for Red Hat OS family (RHEL/CentOS)'
#  import_tasks: os_basic_redhat.yaml
#  when: ansible_os_family|lower == 'redhat'

