---
- name: "deploy rauthy-prerequisites"
  kubernetes.core.k8s:
    state: present
    # src: 'rauthy-prerequisites.yaml'
    # definition: |-
    # template: 'rauthy-prerequisites.yaml.j2'
    # - path: 'file1.j2'
    # - path: 'file2.j2'
- name: "deploy rauthy-app"
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'rauthy-app-service.yaml.j2'
      - path: 'file2.j2'
