---
- name: "k8s_app CloudNativePG"
  when: _k8s_app.version != 'none'
  block:
    - name: "prepare HELM repository for CloudNativePG"
      kubernetes.core.helm_repository:
        release_name: stable
        repo_url: "https://cloudnative-pg.github.io/charts"
    - name: "deploy CloudNativePG"
      kubernetes.core.helm:
        release_name: cnpg
        release_namespace: {{ _k8s_app.namespace | default('cloudnativepg') }}
        release_state: present
        release_values: "{{ lookup('template', 'somefile.yaml') | from_yaml }}"
        wait: true
        create_namespace: true
        chart_ref: cnpg/cloudnativepg
        chart_version: 5.0.12
        update_repo_cache: true

    - name: "deploy prerequisites of CloudNativePG"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg-prerequisites.yaml.j2'
      register: _cloudnativepg_prerequisites
    - name: "deploy CloudNativePG"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg.yaml.j2'
      register: _cloudnativepg_deployment
    - name: "force pod recreation via Rollout (Clean Sledgehammer)"
      when: _cloudnativepg_deployment.changed or _cloudnativepg_prerequisites.changed
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: cloudnativepg-operator
            namespace: "{{ _k8s_app.namespace | default('cloudnativepg') }}"
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
        state: patched
    - name: "configure ingress for cloudnativepg"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg-ingress.yaml.j2'
