###
# based on: https://cloudnative-pg.io/documentation/1.17/installation_upgrade/
---
- name: "k8s_app CloudNativePG"
  when: _k8s_app.version != 'none'
  block:
    

    - name: "deploy prerequisites of CloudNativePG"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg-prerequisites.yaml.j2'
      register: _cloudnativepg_prerequisites
    - name: "deploy CloudNativePG"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg.yaml.j2'
      register: _cloudnativepg_deployment
    - name: "force pod recreation via Rollout (Clean Sledgehammer)"
      when: _cloudnativepg_deployment.changed or _cloudnativepg_prerequisites.changed
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: cloudnativepg-operator
            namespace: "{{ _k8s_app.namespace | default('cloudnativepg') }}"
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
        state: patched
    - name: "configure ingress for cloudnativepg"
      kubernetes.core.k8s:
        state: present
        template: 'cloudnativepg-ingress.yaml.j2'
