---
# - name: "deploy prerequisites"
#  kubernetes.core.k8s:
#    state: present
    # src: 'rauthy-prerequisites.yaml'
    # definition: |-
    # template: 'rauthy-prerequisites.yaml.j2'
    # - path: 'file1.j2'
    # - path: 'file2.j2'

- name: "k8s_app home-assistant"
  when: _k8s_app.version != 'none'
  block:
    - name: "deploy prerequisites of home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant-prerequisites.yaml.j2'
      register: _home_assistant_prerequisites
    - name: "deploy home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant.yaml.j2'
      register: _home_assistant_deployment
    - name: "force pod recreation via Rollout (Clean Sledgehammer)"
      when: _home_assistant_deployment.changed or _home_assistant_prerequisites.changed
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: home-assistant-app
            namespace: "{{ _k8s_app.namespace | default('home-assistant') }}"
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
        state: patched
    - name: "configure ingress for home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant-ingress.yaml.j2'
    - name: "configure local-access ingress for home-assistant"
      when: _k8s_app.local_access is defined and _k8s_app.local_access.enabled
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant-ingress-local-access-{{ _k8s_ingress_detected }}.yaml.j2'
