---
# - name: "deploy prerequisites"
#  kubernetes.core.k8s:
#    state: present
    # src: 'rauthy-prerequisites.yaml'
    # definition: |-
    # template: 'rauthy-prerequisites.yaml.j2'
    # - path: 'file1.j2'
    # - path: 'file2.j2'

- name: "k8s_app home-assistant"
  when: _k8s_app.version != 'none'
  block:
    - name: "deploy prerequisites of home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant-prerequisites.yaml.j2'
    - name: "deploy home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant.yaml.j2'
      register: _home_assistant_deployment
    - name: "force pod recreation (Sledgehammer)"
      when: _home_assistant_deployment.changed
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Pod
        namespace: "{{ _k8s_app.namespace | default('home-assistant') }}"
        name: "home-assistant-app-0"
        wait: yes
        wait_timeout: 60
    - name: "configure ingress for home-assistant"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant-ingress.yaml.j2'
