---
### Kubernetes Reflector didn't work as expected
###
###
# - name: "deploy prerequisites"
#  kubernetes.core.k8s:
#    state: present
    # src: 'rauthy-prerequisites.yaml'
    # definition: |-
    # template: 'rauthy-prerequisites.yaml.j2'
    # - path: 'file1.j2'
    # - path: 'file2.j2'

- name: "k8s_app kubernetes-reflector"
  when: _k8s_app.version != 'none'
  block:
    - name: "deploy app kubernetes-reflector"
      kubernetes.core.k8s:
        state: present
        src: "https://github.com/emberstack/kubernetes-reflector/releases/download/{{ _k8s_app.version }}/reflector.yaml"
    - name: "configure c4m-general reflections"
      kubernetes.core.k8s:
        template: 'kubernetes-reflector-c4m-general.yaml.j2'
        state: present
