---
- name: "Assert that the general default parameters for the role have been defined."
  ansible.builtin.assert:
    that:
      - k8s_apps is not falsy
    fail_msg: "role k8s_apps: general default parameters are not defined!"

- name: "k8s_app kubernetes-reflector"
  when: k8s_apps.kubernetes_reflector is defined and k8s_apps.kubernetes_reflector.version is defined and k8s_apps.kubernetes_reflector.version != 'none'
  import_tasks: kubernetes-reflector.yaml
