---
#- name: "k8s_apps defined"
#  when: k8s_apps is not defined
#  Abbruch und Infomeldung 

- name: "k8s_app kubernetes-reflector"
  when: k8s_apps.kubernetes-reflector is defined and k8s_apps.kubernetes-reflector.version is defined and k8s_apps.kubernetes-reflector.version != 'none'
  import_tasks: kubernetes-reflector.yaml
