---
- name: "Assert that the general default parameters for the role have been defined."
  ansible.builtin.assert:
    that:
      - k8s_apps is not falsy
    fail_msg: "role k8s_apps: general default parameters are not defined!"

#- name: "Check release trains for all K8s Apps"
#  block:
#    - name: Get latest release of a public repository
#      community.general.github_release:
#        user: ansible
#        repo: ansible
#        action: latest_release

- name: "Iterate through K8s applications"
  include_tasks: "{{ _k8s_app.name }}.yaml"
  loop: "{{ k8s_apps }}"
  loop_control:
    loop_var: _k8s_app
    label: "{{ _k8s_app.name }} ({{ _k8s_app.version }})"
