---
# Mosquitto on Kubernetes
# inspired by:
# - https://rohinpandey.medium.com/beginners-guide-mqtt-on-kubernetes-659a6028d8ca
# - https://github.com/abalage/mosquitto-mqtt-k8s
# - https://gist.github.com/gimiki/628e2ca10f026975f00f34e4d1f4ff23

- name: "k8s_app mosquitto"
  when: _k8s_app.version != 'none'
  block:
    - name: "deploy prerequisites of mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'mosquitto-prerequisites.yaml.j2'
      register: _mosquitto_prerequisites
    - name: "deploy mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'mosquitto.yaml.j2'
      register: _mosquitto_deployment
    - name: "force pod recreation via Rollout (Clean Sledgehammer)"
      when: _mosquitto_prerequisites.changed or _mosquitto_deployment.changed
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mosquitto-app
            namespace: "{{ _k8s_app.namespace | default('mosquitto') }}"
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
        state: patched
    - name: "configure ingress for mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'mosquitto-ingress-{{ _k8s_ingress_detected }}.yaml.j2'
