---
# Mosquitto on Kubernetes
# inspired by:
# - https://rohinpandey.medium.com/beginners-guide-mqtt-on-kubernetes-659a6028d8ca
# - https://github.com/abalage/mosquitto-mqtt-k8s
# - https://gist.github.com/gimiki/628e2ca10f026975f00f34e4d1f4ff23

- name: "k8s_app mosquitto"
  when: _k8s_app.version != 'none'
  block:
    - name: "deploy prerequisites of mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'mosquitto-prerequisites.yaml.j2'
    - name: "deploy mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'home-assistant.yaml.j2'
    - name: "configure ingress for mosquitto"
      kubernetes.core.k8s:
        state: present
        template: 'mosquitto-ingress-{{ _ }}.yaml.j2'
