---
# k3s_server:tasks
# inspired by: https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_server/tasks/main.yml
#
# other discussed options:
# - Download and installation: https://github.com/PyratLabs/ansible-role-k3s/blob/main/tasks/build/get-version.yml
- name: Retrieve installed k3s version
  ansible.builtin.command: k3s --version
  register: _cmd_k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Store installed k3s version as additional fact
  when: not ansible_check_mode and _cmd_k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    k3s: "{{ k3s | ansible.builtin.combine({'version_installed': '{{ _cmd_k3s_version_output.stdout_lines[0].split(' ')[2] }}'}) }}"
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/combine_filter.html#ansible-collections-ansible-builtin-combine-filter
    # k3s: "{{ k3s | merge({'version_installed': '{{ _cmd_k3s_version_output.stdout_lines[0].split(' ')[2] }}'}) }}"

### Prepare OS and HW for K3s
- name: Prepare system for K3s
  when: k3s.version_installed is undefined
  become: true # run with sudo
  # become_user: root -> run as root (default)
  # ignore_errors: true
  block:
    - name: Create logical volume on system disk for K3s data
      community.general.lvol:
        vg: "{{ ansible_facts['os_family']|lower + '-vg' | default('ubuntu-vg') }}"
        lv: "k3s-data-lv"
        size: "{{ k3s.storage.data_size }}"
        force: false # never shrink (or remove)
     - name: Format logical volume on system disk for K3s data
       community.general.filesystem:
         fstype: ext4
         dev: "/dev/{{ ansible_facts['os_family']|lower + '-vg' | default('ubuntu-vg') }}/k3s-data-lv"
     - name: Create mountpoint of logical volume for K3s data
       ansible.builtin.file:
         path: "/k3s-data"
         state: directory
         mode: "0755"
     - name: Mount logical volume for K3s data
       ansible.posix.mount:
         path: /k3s-data
         src: "/dev/{{ ansible_facts['os_family']|lower + '-vg' | default('ubuntu-vg') }}/k3s-data-lv"
         fstype: ext4
         state: mounted
     - name: Prepare folders for K3s data
       ansible.builtin.file:
         path: "{{ item.folder }}"
         state: directory
         mode: "0755"
         loop:
           - { folder: "/k3s-data/k3s" }
           - { folder: "/k3s-data/k3s-pods" }
     - name: Prepare folders for K3s data
       ansible.builtin.file:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         state: link
         loop:
           - { src: "/var/lib/rancher/k3s", dest: "/k3s-data/k3s" }
           - { src: "/var/lib/kubelet/pods", dest: "/k3s-data/k3s-pods" }
         # ln -s /datadrive/k3s /var/lib/rancher/k3s
         # ln -s /datadrive/k3s-pods /var/lib/kubelet/pods
         # not done ln -s /datadrive/k3s-run /run/k3s
    - name: Prepare network interfaces for K3s
      

### Download installation sources
# CONDITION: Download installation sources, if:
# a. no K3s has been installed yet (cmd "K3s version" thrown an error)
# b. installed K3s version is older than expected K3s version (var "k3s.version" in cluster's group_vars)
- name: Download installation sources
  when: not ansible_check_mode and (k3s.version_installed is undefined or k3s.version_installed is ansible.builtin.version(k3s.version, '<') )
  become: true
  block:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        # owner: root
        # group: root
        mode: "0755"    
    - name: Download K3s binaries
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        INSTALL_K3S_SKIP_START: "true"
        INSTALL_K3S_VERSION: "{{ k3s.version }}"
      changed_when: true

### Configure all prerequisites of K3s components
# CONDITION: This block should only be executed if no K3s has been installed yet.
- name: Configure all prerequisites of K3s components
  when: not ansible_check_mode and k3s.version_installed is undefined
  become: true # run with sudo
  # become_user: root -> run as root (default)
  # ignore_errors: true
  block:
    - name: Configure prerequistes for K3s network flannel
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: flannel
      when: k3s.network.addon == "flannel"
    - name: Configure prerequistes for K3s storage local-path-provisioner
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: local-path-provisioner
      when: '"local" in k3s.storage.provisioners'
    - name: Configure prerequistes for K3s storage longhorn
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: longhorn
      when: '"longhorn" in k3s.storage.provisioners'
    - name: Configure prerequistes for K3s ingress controller nginx
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: nginx
      when: k3s.ingress.controller == "nginx"
    - name: Configure prerequistes for K3s loadbalancer kube-vip
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: kube-vip
      when: k3s.api.loadbalancer == "kube-vip" or k3s.loadbalancer.addon == "kube-vip"

### Install K3s as server
- import_tasks:
  when: k3s.role == 'server' or k3s.role == 'server-strictly' or default?
- name: 'Prepare K3s configuration file'
      ansible.builtin.include_role:
        name: k3s_cluster
        tasks_from: k3s_cluster_config
        # check: If 3 or more servers are defined, use HA embedded cluster (https://docs.k3s.io/datastore/ha-embedded)
        # location: /etc/rancher/k3s/config.yaml
        # - name: Setup optional config file
        #   when: server_config_yaml is defined
        #   block:
        #     - name: Make config directory
        #       ansible.builtin.file:
        #         path: "/etc/rancher/k3s"
        #         mode: "0755"
        #         state: directory
        #      - name: Copy config values
        #       ansible.builtin.copy:
        #         content: "{{ server_config_yaml }}"
        #         dest: "/etc/rancher/k3s/config.yaml"
        #         mode: "0644"
        #         register: _server_config_result
        # token: ${k3s_token}
        # data-dir: ${k3s_data_dir}
        # flannel-ipv6-masq: true # https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking
        # cluster-cidr: ${k3s_cluster-cidr}
        # service-cidr: ${k3s_service-cidr}
        # node-cidr-mask-size-ipv4: max /12
        # node-cidr-mask-size-ipv6: max /112
    - name: 'Prepare K3s basic services manifests'
        # mkdir -p /var/lib/rancher/k3s/server/manifests/
        # https://docs.k3s.io/installation/packaged-components#auto-deploying-manifests-addons
       #- name: Disable traefik
       #   ansible.builtin.copy:
       #     content: ""
       #     dest: "/var/lib/rancher/k3s/server/manifests/traefik.yaml.skip"
       #     mode: "0644"
       # when: k3s.loadbalancer.use is not "traefik"        

- name: 'Install K3s server (first server)'
  when: inventory_hostname == k3s_cluster | k3s_servers[0] ???
  # INSTALL K3S (but disable service to be able initializing HA cluster)
  # "INSTALL_K3S_SKIP_ENABLE=TRUE INSTALL_K3S_EXEC='server' sh -"      
  # GET K3S KUBECONFIG
  # kubeconfig: /etc/rancher/k3s/k3s.yaml
  # NEW 2025:
  # if kube-vip in use, than: --tls-san
  # if more than 2 server, than: --cluster-init
  

- name: 'Install K3s server (additional server)'
  when: inventory_hostname <> k3s_servers[0]
  # INSTALL K3S (but disable service to be able initializing HA cluster)
  # "INSTALL_K3S_SKIP_ENABLE=TRUE INSTALL_K3S_EXEC='server' sh -"      

# Install K3s as agent
- name: 'import_tasks:
  when: k3s.role == 'agent'
  # INSTALL K3S (but disable service to be able initializing HA cluster)
  # "INSTALL_K3S_SKIP_ENABLE=TRUE INSTALL_K3S_EXEC='agent' sh -"      



# ENABLE CONTAINER FEATURES
# "echo ' cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1' | sudo tee -a /boot/firmware/cmdline.txt",
# 
