---
# k3s_server:tasks
# inspired by: https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_server/tasks/main.yml
#
# other discussed options:
# - Download and installation: https://github.com/PyratLabs/ansible-role-k3s/blob/main/tasks/build/get-version.yml

### Validate key settings
# https://www.puppeteers.net/blog/ansible-quality-assurance-part-1-ansible-variable-validation-with-assert/
- name: Validate K3s cluster definition
  # https://docs.k3s.io/datastore
  # Option a: Single server with SQLite datastore
  # Option b: Three or more server with etcd datastore
  # Option c: Any server with external database datastore (currently not supported by this role)
  # If two server are defined without an external database datastore, than K3s cluster definition is wrong.
  ansible.builtin.assert:
    that:
      - (groups['k3s_servers'] | length == 1) or (groups['k3s_servers'] | length >= 3)
    fail_msg: "ERROR: K3s cluster defintion is wrong (either single server or more than three server has to be defined)"
- name: Validate K3s configuration variable
  ansible.builtin.assert:
    that:
      - k3s is defined
    fail_msg: "ERROR: K3s configuration variable isn't defined"
- name: Validate DNS works and record for K3s API endpoint is available  
  ansible.builtin.assert:
    that:
      - _dns_result | length > 0
    fail_msg: "ERROR: DNS for K3s API endpoint isn't available"
  vars:
    _dns_result: "{{ query('community.dns.lookup', '{{ k3s.api.endpoint }}', type='A') }}"

### Get fact of installed K3s version
- name: Get fact of installed K3s version
  when: not ansible_check_mode
  block:
    - name: Retrieve installed k3s version
      ansible.builtin.command: "k3s --version"
      register: _cmd_k3s_version_output
      changed_when: false
      ignore_errors: true
    - name: Store installed k3s version as additional fact
      when: _cmd_k3s_version_output.rc == 0
      ansible.builtin.set_fact:
        k3s: "{{ k3s | ansible.builtin.combine({'version_installed': _cmd_k3s_version_output.stdout_lines[0].split(' ')[2]}) }}"
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/combine_filter.html#ansible-collections-ansible-builtin-combine-filter
        # k3s: "{{ k3s | merge({'version_installed': '{{ _cmd_k3s_version_output.stdout_lines[0].split(' ')[2] }}'}) }}"

### Prepare OS and HW for K3s
- name: Prepare system for K3s
  when: k3s.version_installed is undefined
  block:
    - name: Prepare folder for K3s configuration
      ansible.builtin.file:
        path: "/etc/rancher/k3s/config.yaml.d"
        mode: "0755"
        state: directory
    - name: Create logical volume on system disk for K3s data
      community.general.lvol:
        vg: "{{ ansible_distribution|lower + '-vg' | default('ubuntu-vg') }}"
        lv: "k3s-data-lv"
        size: "{{ k3s.storage.data_size }}"
        force: false # never shrink (or remove)
    - name: Format logical volume on system disk for K3s data
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/{{ ansible_distribution|lower + '-vg' | default('ubuntu-vg') }}/k3s-data-lv"
      when: not ansible_check_mode
    - name: Create mountpoint of logical volume for K3s data
      ansible.builtin.file:
        path: "/k3s-data"
        state: directory
        mode: "0755"
    - name: Mount logical volume for K3s data
      ansible.posix.mount:
        path: "/k3s-data"
        src: "/dev/{{ ansible_distribution|lower + '-vg' | default('ubuntu-vg') }}/k3s-data-lv"
        fstype: ext4
        state: mounted
      when: not ansible_check_mode
    - name: Prepare folders for K3s data
      ansible.builtin.file:
        path: "{{ item.folder }}"
        state: directory
        mode: "0755"
      loop:
        - { folder: "/var/lib/rancher/k3s" }
        - { folder: "/var/lib/kubelet/pods" }
      when: not ansible_check_mode
    - name: Prepare folders for K3s data
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { src: "/var/lib/rancher/k3s", dest: "/k3s-data/k3s" }
        - { src: "/var/lib/kubelet/pods", dest: "/k3s-data/k3s-pods" }
      when: not ansible_check_mode
        # ln -s /datadrive/k3s /var/lib/rancher/k3s
        # ln -s /datadrive/k3s-pods /var/lib/kubelet/pods
        # not done ln -s /datadrive/k3s-run /run/k3s
    - name: Prepare user bashrc for K3s autocomplete
      when: ansible_user is defined
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        regexp: '\.\s+<\(k3s completion bash\)'
        line: ". <(k3s completion bash)  # Added by k3s-ansible"

### Download installation sources and install binareies
# CONDITION: Download installation sources and install binaries, if:
# a. no K3s has been installed yet (cmd "K3s version" thrown an error)
# b. installed K3s version is older than expected K3s version (var "k3s.version" in cluster's group_vars)
- name: Download installation sources
  when: k3s.version_installed is undefined or k3s.version_installed is ansible.builtin.version(k3s.version, '<')
  block:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: "https://get.k3s.io/"
        timeout: 120
        dest: "/usr/local/bin/k3s-install.sh"
        # owner: root
        # group: root
        mode: "0755"    
    - name: Install K3s binaries
      # INSTALL K3S (but disable service to be able initializing HA cluster)
      # "INSTALL_K3S_SKIP_ENABLE=TRUE INSTALL_K3S_EXEC='server' sh -" 
      ansible.builtin.command:
        cmd: "/usr/local/bin/k3s-install.sh"
      environment:
        INSTALL_K3S_SKIP_START: "true"
        INSTALL_K3S_VERSION: "{{ k3s.version }}"
      changed_when: true
      when: not ansible_check_mode
      register: _k3s_binaries_installed

### Configure all node-level prerequisites of K3s components
# mkdir -p /var/lib/rancher/k3s/server/manifests/
# https://docs.k3s.io/installation/packaged-components#auto-deploying-manifests-addons
- name: Configure all prerequisites of K3s components
  # become_user: root -> run as root (default)
  # ignore_errors: true
  block:
    - name: Configure prerequisites for K3s network flannel
      when: k3s.networking.addon == 'flannel'
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: flannel_node-level
    - name: Configure prerequisites for K3s storage local-path-provisioner
      when: "'local' in (k3s.storage.provisioners | default([]))"
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: local-path-provisioner_node-level
    - name: Configure prerequisites for K3s storage longhorn
      when: "'longhorn' in (k3s.storage.provisioners | default([]))"
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: longhorn_node-level
    - name: Configure prerequisites for K3s ingress controller nginx
      when: k3s.ingress.controller == 'nginx'
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: nginx_node-level
    - name: Configure prerequisites for K3s ingress controller traefik
      when: k3s.ingress.controller == 'traefik'
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: traefik_node-level
    - name: Configure prerequisites for K3s loadbalancer kube-vip
      when: k3s.api.loadbalancer == 'kube-vip' or k3s.loadbalancer.addon == 'kube-vip'
      ansible.builtin.include_role:
        name: k3s_components
        tasks_from: kube-vip_node-level

### Configure K3s server
# Configuration:
# - K3s environment variables for installation "INSTALL_K3S_": used by install-script
# - K3s environment variables for configuratoin "K3S_": /etc/systemd/system/k3s.service.env
# --- Environment variables which begin with K3S_ will be preserved for the systemd and openrc services to use.
# - K3s configuration flags "--xyz-": /etc/rancher/k3s/config.yaml & /etc/rancher/k3s/config.yaml.d/*.yaml
# --- In addition to configuring K3s with environment variables and CLI arguments, K3s can also use a config file. (https://docs.k3s.io/installation/configuration#configuration-file)
# --- Options are documented on this page as CLI flags, but can also be passed as configuration file options (https://docs.k3s.io/cli/server). 
# - [good to know, not imported] K3s Containerd Base Template: #/var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.tmpl -> Extend with instruction: https://docs.k3s.io/advanced#base-template
# Defintiion:
# - Use ansible environment variables for installation
# - Use configuration files for configuration
- name: Write config for any K3s server
  # token: write token to configuration file
  # data-dir: nothing to do, because data-dir have been redirected on system level (see above)
##### needs to be done
  # cluster-cidr: ${k3s_cluster-cidr}
  # service-cidr: ${k3s_service-cidr}
  # node-cidr-mask-size-ipv4: max /12
  # node-cidr-mask-size-ipv6: max /112
  # flannel-ipv6-masq: true # https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking
  # firewalling: https://docs.k3s.io/installation/requirements?os=debian#inbound-rules-for-k3s-nodes
  # - ufw: ufw allow 6443/tcp #apiserver / ufw allow from 10.42.0.0/16 to any #pods / ufw allow from 10.43.0.0/16 to any #services
##### /needs to be done
  block:
    - name: Create an empty K3s config file, if no file is available
      ansible.builtin.file:
        path: "/etc/rancher/k3s/config.yaml.d/00-k3s-server.yaml"
        state: touch
    - name: Delete any existing token from the environment if different from the new one
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/rancher/k3s/config.yaml.d/00-k3s-server.yaml"
        regexp: "^token: \\s*(?!{{ k3s.token | default('') | regex_escape }}\\s*$)"
      register: _k3s_config
      # Add the token to the environment if it has been provided.
    - name: Add token as an environment variable
      when: not ansible_check_mode and k3s.token is defined
      no_log: true # avoid logging the server token
      ansible.builtin.lineinfile:
        path: "/etc/rancher/k3s/config.yaml.d/00-k3s-server.yaml"
        line: "token: {{ k3s.token }}"
      register: _k3s_config

- name: Write config for HA embedded architecture (3 or more servers, etcd datastore)
  # if 3 or more servers are defined, use HA embedded cluster (https://docs.k3s.io/datastore/ha-embedded) => --cluster-init
  # if Load Balancer for  in use, than: --tls-san
  when: (groups['k3s_servers'] | length) >= 3
  block:
    - name: Write config for first server
      when: inventory_hostname == groups['k3s_servers'][0]
      ansible.builtin.copy:
        content: "cluster-init: true"
        dest: "/etc/rancher/k3s/config.yaml.d/10-ha-embedded.yaml"
        mode: "0644"
      register: _k3s_config
    - name: Write config for first server, if API is loadbalanced
      when: inventory_hostname == groups['k3s_servers'][0]
      ansible.builtin.template:
        src: k3s-server-20-api-loadbalanced.yaml.j2
        dest: "/etc/rancher/k3s/config.yaml.d/20-api-loadbalanced.yaml"
        owner: root
        group: root
        mode: "0644"
      register: _k3s_config
    - name: Write config for subsequent servers
      when: inventory_hostname != groups['k3s_servers'][0]
      ansible.builtin.copy:
        content: "server: 'https://{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}:{{ k3s.api.port | default('6443') }}'"
        dest: "/etc/rancher/k3s/config.yaml.d/10-ha-embedded.yaml"
        mode: "0644"
      register: _k3s_config

- name: Write K3s service file
  ansible.builtin.template:
    src: "k3s-server.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    mode: "0644"
  register: _k3s_service

### (Re-)Start K3s service
- name: Restart K3s service
  when:
    - ansible_facts.services['k3s.service'] is defined
    - ansible_facts.services['k3s.service'].state == 'running'
    - _k3s_service.changed or _k3s_config.changed or _k3s_binaries_installed.changed
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
- name: Enable and check K3s service
  when: not ansible_check_mode and (ansible_facts.services['k3s.service'] is not defined or ansible_facts.services['k3s.service'].state != 'running')
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true
- name: Pause to allow first server startup
  when:
    - (groups['k3s_servers'] | length) >= 3
    - inventory_hostname == groups['k3s_servers'][0]
  ansible.builtin.pause:
    seconds: 30

###########
# GET K3S KUBECONFIG: -> kubeconfig: /etc/rancher/k3s/k3s.yaml
- name: Download kubeconfig of first server to the Ansible control node
  when: inventory_hostname == groups['k3s_servers'][0]
  become: false
  block:
    - name: Create kubeconfig folder
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
      delegate_to: localhost
    - name: Download kubeconfig
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "~/.kube/config-{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}.original"
        flat: true
      become: true
      register: _control_node_kubeconfig_original
    - name: Prepare kubeconfig for control node
      when: _control_node_kubeconfig_original.changed
      block:
        - name: Copy K3s kubeconfig original to final
          ansible.builtin.copy:
            src: "~/.kube/config-{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}.original"
            dest: "~/.kube/config-{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}"
          delegate_to: localhost
        - name: Set K3s API endpoint for remote access
          ansible.builtin.replace:
            path: "~/.kube/config-{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}"
            regexp: 'server: https://[0-9.]+:\d+'
            replace: "server: 'https://{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}:{{ k3s.api.port | default('6443') }}'"
          delegate_to: localhost
    - name: Configure default KUBECONFIG for user
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        regexp: '^export KUBECONFIG=(.*)$'
        insertafter: '^export KUBECONFIG=(.*)$'
        line: "export KUBECONFIG=~/.kube/config-{{ k3s.api.endpoint | default(groups['k3s_servers'][0]) }}:$KUBECONFIG"
      delegate_to: localhost
    - name: Configure kubectl autocomplete
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        regexp: '\.\s+<\(kubectl completion bash\)'
        line: ". <(kubectl completion bash)  # Added by k3s-ansible"
      delegate_to: localhost
