---
# cloudia-4man (c4m) playbook
# 
# inventory: defines configuration items (ci), or groups of configuration items (gci)
# role: defines configuration tasks for a specific type of configuration item
# playbook: maps roles to ci or cgi
#
# keep in mind:
# - inventory is ordered: first hosts/groups are executed first.
# - roles are ordered: first role will be applied first.
# - playbook are ordered: first playbook definition will be applied first.
# 
# further readings:
# - https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# - https://www.digitalocean.com/community/tutorials/how-to-use-ansible-roles-to-abstract-your-infrastructure-environment
# - https://stackoverflow.com/questions/42386801/ansible-how-to-control-the-order-of-the-hosts-when-playbook-is-ran
# - https://stackoverflow.com/questions/42506865/ansible-play-with-hosts-in-order-i-desire


#- import_playbook: zigbee2mqtt.yaml
- hosts: zigbee2mqtt_proxies
  gather_facts: yes
  roles:
    - role: os_basic
    - role: zigbee2mqtt_proxy

#- import_playbook: plain.yaml
- hosts: plain_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic

# - import_playbook: k3s.yaml
- hosts: k3s_servers
  serial: 1
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_server
      # task for first server: when: inventory_hostname == k3s_servers[0]

- hosts: k3s_agents
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_agent
