---
# hosts: always multiply of main role name

#- import_playbook: plain.yml
- hosts: plain_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic

# - import_playbook: k3s.yml
- hosts: k3s_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_server

- hosts: k3s_nodes
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_node
