---
# hosts: always multiply of main role name

#- import_playbook: raspberrypi.yaml
- hosts: raspberrypi_4_devices
  gather_facts: no
  roles:
    - role: raspberrypi_4_device

#- import_playbook: plain.yaml
- hosts: plain_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic

# - import_playbook: k3s.yaml
- hosts: k3s_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_server

- hosts: k3s_nodes
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_node
