---
# hosts: always multiply of main role name

#- import_playbook: zigbee2mqtt.yaml
- hosts: zigbee2mqtt_proxies
  gather_facts: yes
  roles:
    - role: os_basic
    - role: zigbee2mqtt_proxy

#- import_playbook: plain.yaml
- hosts: plain_servers
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic

# - import_playbook: k3s.yaml
- hosts: k3s_servers
  serial: 1
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_server
      # task for first server: when: inventory_hostname == k3s_servers[0]

- hosts: k3s_nodes
  gather_facts: yes
  become: yes
  roles:
    - role: os_basic
    - role: k3s_node
